# Generated by Django 3.1.4 on 2020-12-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='owner',
        ),
    ]
