# Generated by Django 3.1.4 on 2020-12-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_remove_vendor_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
