export const ADD_VENDORS = 'ADD_VENDORS'
export const EDIT_VENDOR = 'EDIT_VENDOR'
export const ADD_VENDOR = 'ADD_VENDOR'
export const DELETE_VENDOR = 'DELETE_VENDOR'
export const VENDOR_LOADING = 'VENDOR_LOADING'
export const VENDOR_FAILED = 'VENDOR_FAILED'

export const ADD_SHOPS = 'ADD_SHOPS'
export const ADD_SHOP = 'ADD_SHOP'
export const SHOP_LOADING = 'SHOP_LOADING'
export const SHOP_FAILED = 'SHOP_FAILED'
